import {StyleSheet} from 'react-native';
import Colors from '@Constants/Colors';

export default StyleSheet.create({
  mainContainerLoading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mainContainer: {
    flex: 1,
  },
  flatListContainer: {
    width: 353,
    height: 350,
    backgroundColor: Colors.white,
    alignSelf: 'center',
    borderRadius: 10,
  },
  welcomeText: {
    color: Colors.blackText,
    fontWeight: '800',
    fontSize: 20,
    lineHeight: 27.32,
    marginLeft: 20,
    fontFamily: 'Avenir',
  },
  nameText: {
    color: Colors.blackText,
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 21.86,
    marginBottom: 20,
    marginLeft: 20,
    fontFamily: 'Avenir',
  },
  yourPoints: {
    color: Colors.grayText,
    fontWeight: '800',
    fontSize: 14,
    lineHeight: 19.12,
    marginLeft: 20,
    marginBottom: 20,
    fontFamily: 'Avenir',
  },
  yourMovements: {
    color: Colors.grayText,
    fontFamily: 'Avenir',
    fontWeight: '800',
    fontSize: 14,
    lineHeight: 19.12,
    marginLeft: 20,
    marginBottom: 20,
    marginTop: 20,
  },
  bigButton: {
    width: 353,
    height: 50,
    backgroundColor: Colors.buttonBlue,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    alignSelf: 'center',
  },
  smallButton: {
    width: 170,
    height: 50,
    backgroundColor: Colors.buttonBlue,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonsContainer: {
    marginTop: 20,
    width: 353,
    justifyContent: 'space-around',
    flexDirection: 'row',
    alignSelf: 'center',
  },
  bigButtonText: {
    color: Colors.white,
    fontFamily: 'Avenir',
    fontWeight: '800',
    fontSize: 16,
    lineHeight: 22,
  },
  smallButtonText: {
    color: Colors.white,
    fontFamily: 'Avenir',
    fontWeight: '800',
    fontSize: 12,
    lineHeight: 16,
  },
});
